server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8079/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: loansServiceId
          uri: lb://LOAN
          predicates:
            - Path=/loans/**
          filters:
            - AuthFilter
        - id: userServiceId
          uri: lb://USER
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter
        - id: authServiceId
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
#        - id: swagger
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#          uri: http://localhost:${server.port}
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /user/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: /loan/v3/api-docs
        name: Loan Service
        primaryName: Loan Service
      - url: /auth/v3/api-docs
        name: Auth Service
        primaryName: Auth Service